#!/bin/bash
# This script sets the default /etc/network/interfaces config back in place

echo "Restoring default /etc/network/interfaces file..."
echo "# Generated by RaspiPass set_interfaces.sh" > /etc/network/interfaces
echo "# This file describes the network interfaces available on your system" >> /etc/network/interfaces
echo "# and how to activate them. For more information, see interfaces(5)." >> /etc/network/interfaces
echo "" >> /etc/network/interfaces
echo "# The loopback network interface" >> /etc/network/interfaces
echo "auto lo" >> /etc/network/interfaces
echo "iface lo inet loopback" >> /etc/network/interfaces
echo "" >> /etc/network/interfaces
echo "# Configure eth0 and wlan0" >> /etc/network/interfaces
echo "allow-hotplug eth0" >> /etc/network/interfaces
echo "auto eth0" >> /etc/network/interfaces
echo "iface eth0 inet manual" >> /etc/network/interfaces
echo "auto wlan0" >> /etc/network/interfaces
echo "iface wlan0 inet manual" >> /etc/network/interfaces
echo "" >> /etc/network/interfaces
echo "# Configure bridge and add eth0" >> /etc/network/interfaces
echo "auto br0" >> /etc/network/interfaces
echo "iface br0 inet dhcp" >> /etc/network/interfaces
echo "    bridge_ports eth0" >> /etc/network/interfaces
echo "    bridge_stp on" >> /etc/network/interfaces
echo "" >> /etc/network/interfaces
echo "# Load iptables rules before bringing up interfaces" >> /etc/network/interfaces
echo "pre-up iptables-restore < /raspi_secure/firewall.rules" >> /etc/network/interfaces
echo "Done - restart networking or reboot to re-read configuration."
